name: build and release

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup go
        uses: actions/setup-go@v3
        with:
          go-version: '1.24'

      - name: Install dependencies
        run: |
          go mod tidy

      - name: Test app endpoints
        run: |
          go run main.go &
          
          sleep 3
          
          curl -f http://localhost:8080/ || exit 1
          
          curl -f https://localhost:8080/hello || exit 1
  build_and_release:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Build
        run: |
          go build -o main.go
      - name: Release
        run: |
          RELEASE_TAG="v$(date + '%Y%m%d%H%M%S')"
          gh release create $RELEASE_TAG main -- title "Release $RELEASE_TAG" --notes "Build and released" --repo $GITHUB_REPOSITORY
          gh release upload $RELEASE_TAG main --repo $GITHUB_REPOSITORY